# Generated by Django 5.1.7 on 2025-06-30 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productvariant_productimage_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitors', models.IntegerField(default=0)),
                ('product_views', models.IntegerField(default=0)),
                ('add_to_cart', models.IntegerField(default=0)),
                ('checkout_started', models.IntegerField(default=0)),
                ('orders_completed', models.IntegerField(default=0)),
                ('product_view_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('add_to_cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('checkout_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('favorite_category', models.CharField(blank=True, max_length=100)),
                ('favorite_brand', models.CharField(blank=True, max_length=100)),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('period', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='TopSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rank', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['rank', '-revenue'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('email', 'Email Campaign'), ('referral', 'Referral'), ('paid_ads', 'Paid Ads')], max_length=50)),
                ('date', models.DateField()),
                ('visitors', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('source', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('add_to_cart', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
