# Generated by Django 5.1.7 on 2025-06-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(choices=[('personal_shopping', 'Personal Shopping'), ('product_sourcing', 'Product Sourcing'), ('styling_consultation', 'Styling Consultation'), ('authentication', 'Authentication Service'), ('customization', 'Customization Request'), ('gift_service', 'Gift Service'), ('vip_appointment', 'VIP Appointment'), ('other', 'Other Request')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Standard'), ('medium', 'Priority'), ('high', 'Urgent'), ('vip', 'VIP Client')], default='low', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('preferred_contact', models.CharField(default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concierge Request',
                'verbose_name_plural': 'Concierge Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
